### ISSUE TITLE
Production build crashes: "X is not a function" (Set/Map lost after minification)

### ISSUE THREAD

**Issue by TrevorBurnham** [brimdata/react-arborist#348]
## Summary

Multiple reports of runtime crashes that only appear in production/minified builds (Next.js, Docker, Tanstack Start), where an internal `Set`/`Map` appears to lose its methods — e.g. `clear`/`set`/`get` "is not a function". Likely a bundling/minification or duplicated-instance issue rather than user error.

## Rolls up

- #155 "TypeError: r_.clear is not a function" in Docker container
- #165 Using Next.js in Vercel has compilation issues (`rP.set is not a function`)
- #301 Uncaught TypeError: Cannot read properties of undefined (reading "tree") (React 19 / Tanstack Start)

Goal: a minimal reproduction + root-cause across these environments.

**Comment by TrevorBurnham** [comment]
**Root-caused. This tracks two unrelated problems — both now resolved.**

**1. `X.clear` / `X.set` / `X.only` "is not a function" in minified builds (#155, #165)**

An external **SWC minifier bug** ([swc-project/swc#7664](https://github.com/swc-project/swc/discussions/7664)), not a library defect. All three failing calls are methods of the single `selection` actions object dispatched from `setSelection`/`deselectAll`; SWC mangled that object's properties in certain production configs (Docker, older Vercel/Next). It reproduces only with the buggy minifier — a plain `next build && next start` works.

Fixed upstream: use **Next.js ≥ 13.4.14** (patched SWC), or `swcMinify: false` on older versions. I couldn't reproduce it on current Next/SWC or in a Vite SSR build with either react-arborist 3.13.0 or 3.4.3.

**2. `Cannot read properties of undefined (reading 'tree')` — React 19 / Tanstack Start (#301)**

This one *was* a library footgun, and it's now **fixed in #374** (shipping in the next release). `NodeApi`'s action methods (`toggle`, `select`, `activate`, …) were plain prototype methods, so passing one as a bare callback — e.g. `<Toggle onClick={node.toggle} />`, as a custom node renderer naturally does — detached `this`, and `this.tree` threw. They're now bound to the instance, so `node.toggle` & friends work when passed by reference. (`node.toggle()` still works exactly as before.)

I confirmed this against a Tanstack-Start-shaped repro (React 19 + Vite SSR + hydration): the crash reproduced before the fix and is gone after.

**Workaround for anyone on an older version:** wrap the call — `onClick={() => node.toggle()}` — or bind it yourself.

Closing as resolved. If you hit the minified-build crash on Next ≥ 13.4.14, please open a fresh issue with the exact toolchain versions.
